#!/bin/sh
# pir interactive deployment (QA style).
#
# Asks for every deployment decision that has no safe default, writes .env
# (chmod 600), brings up the docker compose service, and verifies it:
#
#   sh docker/deploy.sh
#
# LLM agents may either run this script interactively on the user's behalf
# or ask the same questions themselves — docs/for-llm.md documents each
# question, its default and its validation rules.
set -e

HERE=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
ENV_FILE="$HERE/.env"
PIR_IMAGE=${PIR_IMAGE:-ghcr.io/beiyanpiki/pir:main}
THINKING_LEVELS="off minimal low medium high xhigh max"

say() { printf '%s\n' "$*" >&2; }
ask() { # ask <prompt> <default> -> ANSWER (empty answer keeps the default)
  printf '%s' "$1 [$2]: " >&2
  read -r ANSWER
  ANSWER=${ANSWER:-$2}
}
ask_secret() { # like ask but never echoes a default secret
  printf '%s' "$1: " >&2
  read -r ANSWER
}
pick_one() { # pick_one <prompt> <default> <list...> -> ANSWER (number, or raw id)
  _prompt=$1
  _default=$2
  shift 2
  _n=0
  for _item in "$@"; do
    _n=$((_n + 1))
    say "  $_n) $_item"
  done
  while :; do
    ask "$_prompt" "$_default"
    case $ANSWER in
      ''|*[!0-9]*) # not a number: treat as a typed id
        [ -n "$ANSWER" ] && return 0
        ;;
      *)
        if [ "$ANSWER" -ge 1 ] && [ "$ANSWER" -le $_n ]; then
          _i=0
          for _item in "$@"; do
            _i=$((_i + 1))
            [ "$_i" -eq "$ANSWER" ] && { ANSWER=$_item; return 0; }
          done
        fi
        ;;
    esac
    say "  invalid choice"
  done
}

say "pir deployment — interactive configuration"
say "=========================================="

# The model picker enumerates the catalog from the container image itself.
say "Pulling $PIR_IMAGE (needed to list models) ..."
if docker pull "$PIR_IMAGE" 2>/dev/null; then
  PIR_LIST="docker run --rm $PIR_IMAGE"
else
  say "  pull failed — falling back to manual provider/model entry"
  PIR_LIST=""
fi

# Q1 — shared secret protecting the HTTPS executor endpoint.
say ""
say "Q1/4 — Bearer token for the HTTPS API."
say "  Press Enter to generate a random one with openssl."
TOKEN=""
while [ -z "$TOKEN" ]; do
  ask_secret "  PIR_SERVER_TOKEN (or Enter to generate)"
  if [ -z "$ANSWER" ]; then
    TOKEN=$(openssl rand -hex 16 2>/dev/null || echo "pir-$(date +%s)-change-me")
    say "  generated: $TOKEN"
  else
    TOKEN=$ANSWER
  fi
done

# Q2 — model access: pick any pi provider, a model and its API key.
say ""
say "Q2/4 — Model access."
say "  pir reviews through any provider supported by pi"
say "  (anthropic, openai, deepseek, zai-coding-cn, moonshotai-cn, ...)."
say "  The key is injected as PI_AUTH_JSON and stored in .env (chmod 600) —"
say "  it is never baked into the image or committed to git."
PROVIDERS=""
if [ -n "$PIR_LIST" ]; then
  PROVIDERS=$($PIR_LIST models --ids --all 2>/dev/null | cut -d/ -f1 | sort -u || true)
fi
if [ -n "$PROVIDERS" ]; then
  say "  Providers in the pi catalog:"
  # shellcheck disable=SC2086
  pick_one "  provider (number or id)" "zai-coding-cn" $PROVIDERS
  PROVIDER=$ANSWER
else
  ask "  provider id (e.g. zai-coding-cn)" "zai-coding-cn"
  PROVIDER=$ANSWER
fi
MODELS=""
if [ -n "$PIR_LIST" ]; then
  MODELS=$($PIR_LIST models --ids --all --provider "$PROVIDER" 2>/dev/null | sed "s|^[^/]*/||" || true)
fi
if [ -n "$MODELS" ]; then
  say "  Models for $PROVIDER:"
  # shellcheck disable=SC2086
  pick_one "  model (number or id)" "" $MODELS
  MODEL=$ANSWER
else
  ask "  model id for $PROVIDER" "glm-5.3-flash"
  MODEL=$ANSWER
fi
API_KEY=""
while [ -z "$API_KEY" ]; do
  ask_secret "  API key for $PROVIDER"
  API_KEY=$ANSWER
done
ask "  thinking level ($THINKING_LEVELS, Enter = image default)" ""
THINKING=$ANSWER
while [ -n "$THINKING" ]; do
  case " $THINKING_LEVELS " in *" $THINKING "*) break ;; esac
  say "  invalid thinking level: $THINKING"
  ask "  thinking level ($THINKING_LEVELS, Enter = image default)" ""
  THINKING=$ANSWER
done

# Q3 — published port.
say ""
say "Q3/4 — Public port for the HTTPS service."
ask "  port" "8790"
PORT=$ANSWER
case $PORT in
  ''|*[!0-9]*) say "invalid port: $PORT"; exit 2 ;;
esac

# Q4 — TLS strategy. Self-signed covers most deployments; custom PEM pairs
# are documented in docs/for-llm.md (mount + PIR_TLS_CERT/PIR_TLS_KEY).
say ""
say "Q4/4 — TLS certificate."
say "  self  : auto-generate with openssl (clients pass --insecure)"
say "  custom: use your own PEM pair via PIR_TLS_CERT/PIR_TLS_KEY (advanced)"
ask "  TLS mode (self|custom)" "self"
case $ANSWER in
  custom) say "  note: see docs/for-llm.md — using self-signed for now"; TLS_MODE="custom" ;;
  *) TLS_MODE="self" ;;
esac

say ""
say "Writing $ENV_FILE (chmod 600) ..."
umask 177
{
  echo "# Generated by docker/deploy.sh — $(date -u +%FT%TZ)"
  echo "PIR_SERVER_TOKEN=$TOKEN"
  echo "PI_AUTH_JSON={\"$PROVIDER\":{\"type\":\"api_key\",\"key\":\"$API_KEY\"}}"
  echo "PI_DEFAULT_PROVIDER=$PROVIDER"
  echo "PI_DEFAULT_MODEL=$MODEL"
  [ -n "$THINKING" ] && echo "PI_DEFAULT_THINKING=$THINKING"
  echo "PIR_PORT=$PORT"
} > "$ENV_FILE"
umask 022

say "Starting the service (docker compose up -d) ..."
docker compose -f "$HERE/docker-compose.yml" --env-file "$ENV_FILE" up -d

say "Waiting for /health ..."
i=0
while [ $i -lt 30 ]; do
  if curl -sk "https://localhost:$PORT/health" >/dev/null 2>&1; then break; fi
  i=$((i + 1)); sleep 1
done
HEALTH=$(curl -sk "https://localhost:$PORT/health") || {
  say "service did not become healthy; inspect: docker compose logs"
  exit 3
}
say "healthy: $HEALTH"

say "Verifying model access ($PROVIDER/$MODEL) ..."
EXEC=$(curl -sk \
  -H "Authorization: Bearer $TOKEN" \
  -H 'content-type: application/json' \
  -d '{"argv":["models","--ids"]}' \
  "https://localhost:$PORT/v1/exec" || true)
if printf '%s' "$EXEC" | grep -qF "$PROVIDER/$MODEL"; then
  say "model ready: $PROVIDER/$MODEL"
else
  say "warning: server did not list $PROVIDER/$MODEL; inspect: docker compose logs"
fi

say ""
say "Deployment verified. Quick start:"
say "  pir --server https://localhost:$PORT --token '$TOKEN' --insecure version"
say "  cd /your/project"
say "  pir --server https://localhost:$PORT --token '$TOKEN' --insecure find --uncommitted --json"
