#!/bin/sh
# pir interactive deployment (QA style).
#
# Asks for every deployment decision that has no safe default, writes .env
# (chmod 600), brings up the docker compose service, and verifies it:
#
#   sh docker/deploy.sh
#
# LLM agents may either run this script interactively on the user's behalf
# or ask the same questions themselves — docs/for-llm.md documents each
# question, its default and its validation rules.
set -e

HERE=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
ENV_FILE="$HERE/.env"

say() { printf '%s\n' "$*" >&2; }
ask() { # ask <prompt> <default> -> ANSWER (empty answer keeps the default)
  printf '%s' "$1 [$2]: " >&2
  read -r ANSWER
  ANSWER=${ANSWER:-$2}
}
ask_secret() { # like ask but never echoes a default secret
  printf '%s' "$1: " >&2
  read -r ANSWER
}

say "pir deployment — interactive configuration"
say "=========================================="

# Q1 — shared secret protecting the HTTPS executor endpoint.
say ""
say "Q1/4 — Bearer token for the HTTPS API."
say "  Press Enter to generate a random one with openssl."
TOKEN=""
while [ -z "$TOKEN" ]; do
  ask_secret "  PIR_SERVER_TOKEN (or Enter to generate)"
  if [ -z "$ANSWER" ]; then
    TOKEN=$(openssl rand -hex 16 2>/dev/null || echo "pir-$(date +%s)-change-me")
    say "  generated: $TOKEN"
  else
    TOKEN=$ANSWER
  fi
done

# Q2 — model credentials (official Zhipu bigmodel coding endpoint).
say ""
say "Q2/4 — Model access."
say "  pir reviews through the official GLM coding endpoint"
say "  (open.bigmodel.cn, pi's built-in zai-coding-cn provider)."
say "  The key is injected as an env var and stored in .env (chmod 600) —"
say "  it is never baked into the image or committed to git."
BIGMODEL_KEY=""
while [ -z "$BIGMODEL_KEY" ]; do
  ask_secret "  BIGMODEL_API_KEY (your bigmodel coding-plan key)"
  BIGMODEL_KEY=$ANSWER
done

# Q3 — published port.
say ""
say "Q3/4 — Public port for the HTTPS service."
ask "  port" "8790"
PORT=$ANSWER
case $PORT in
  ''|*[!0-9]*) say "invalid port: $PORT"; exit 2 ;;
esac

# Q4 — TLS strategy. Self-signed covers most deployments; custom PEM pairs
# are documented in docs/for-llm.md (mount + PIR_TLS_CERT/PIR_TLS_KEY).
say ""
say "Q4/4 — TLS certificate."
say "  self  : auto-generate with openssl (clients pass --insecure)"
say "  custom: use your own PEM pair via PIR_TLS_CERT/PIR_TLS_KEY (advanced)"
ask "  TLS mode (self|custom)" "self"
case $ANSWER in
  custom) say "  note: see docs/for-llm.md — using self-signed for now"; TLS_MODE="custom" ;;
  *) TLS_MODE="self" ;;
esac

say ""
say "Writing $ENV_FILE (chmod 600) ..."
umask 177
{
  echo "# Generated by docker/deploy.sh — $(date -u +%FT%TZ)"
  echo "PIR_SERVER_TOKEN=$TOKEN"
  echo "BIGMODEL_API_KEY=$BIGMODEL_KEY"
  echo "PIR_PORT=$PORT"
} > "$ENV_FILE"
umask 022

say "Starting the service (docker compose up -d) ..."
docker compose -f "$HERE/docker-compose.yml" --env-file "$ENV_FILE" up -d

say "Waiting for /health ..."
i=0
while [ $i -lt 30 ]; do
  if curl -sk "https://localhost:$PORT/health" >/dev/null 2>&1; then break; fi
  i=$((i + 1)); sleep 1
done
HEALTH=$(curl -sk "https://localhost:$PORT/health") || {
  say "service did not become healthy; inspect: docker compose logs"
  exit 3
}
say "healthy: $HEALTH"
say ""
say "Deployment verified. Quick start:"
say "  pir --server https://localhost:$PORT --token '$TOKEN' --insecure version"
say "  cd /your/project"
say "  pir --server https://localhost:$PORT --token '$TOKEN' --insecure find --uncommitted --json"
